# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quentin/Documents/4SI2/pair/pairOculus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quentin/Documents/4SI2/pair/pairOculus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quentin/Documents/4SI2/pair/pairOculus/CMakeFiles /home/quentin/Documents/4SI2/pair/pairOculus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quentin/Documents/4SI2/pair/pairOculus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pairOculus

# Build rule for target.
pairOculus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pairOculus
.PHONY : pairOculus

# fast build rule for target.
pairOculus/fast:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/build
.PHONY : pairOculus/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/main.cpp.s
.PHONY : main.cpp.s

server.o: server.cpp.o
.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i
.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s
.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.s
.PHONY : server.cpp.s

src/Block.o: src/Block.cpp.o
.PHONY : src/Block.o

# target to build an object file
src/Block.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Block.cpp.o
.PHONY : src/Block.cpp.o

src/Block.i: src/Block.cpp.i
.PHONY : src/Block.i

# target to preprocess a source file
src/Block.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Block.cpp.i
.PHONY : src/Block.cpp.i

src/Block.s: src/Block.cpp.s
.PHONY : src/Block.s

# target to generate assembly for a file
src/Block.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Block.cpp.s
.PHONY : src/Block.cpp.s

src/BlockFactory.o: src/BlockFactory.cpp.o
.PHONY : src/BlockFactory.o

# target to build an object file
src/BlockFactory.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/BlockFactory.cpp.o
.PHONY : src/BlockFactory.cpp.o

src/BlockFactory.i: src/BlockFactory.cpp.i
.PHONY : src/BlockFactory.i

# target to preprocess a source file
src/BlockFactory.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/BlockFactory.cpp.i
.PHONY : src/BlockFactory.cpp.i

src/BlockFactory.s: src/BlockFactory.cpp.s
.PHONY : src/BlockFactory.s

# target to generate assembly for a file
src/BlockFactory.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/BlockFactory.cpp.s
.PHONY : src/BlockFactory.cpp.s

src/Bomb.o: src/Bomb.cpp.o
.PHONY : src/Bomb.o

# target to build an object file
src/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Bomb.cpp.o
.PHONY : src/Bomb.cpp.o

src/Bomb.i: src/Bomb.cpp.i
.PHONY : src/Bomb.i

# target to preprocess a source file
src/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Bomb.cpp.i
.PHONY : src/Bomb.cpp.i

src/Bomb.s: src/Bomb.cpp.s
.PHONY : src/Bomb.s

# target to generate assembly for a file
src/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Bomb.cpp.s
.PHONY : src/Bomb.cpp.s

src/BombManager.o: src/BombManager.cpp.o
.PHONY : src/BombManager.o

# target to build an object file
src/BombManager.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/BombManager.cpp.o
.PHONY : src/BombManager.cpp.o

src/BombManager.i: src/BombManager.cpp.i
.PHONY : src/BombManager.i

# target to preprocess a source file
src/BombManager.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/BombManager.cpp.i
.PHONY : src/BombManager.cpp.i

src/BombManager.s: src/BombManager.cpp.s
.PHONY : src/BombManager.s

# target to generate assembly for a file
src/BombManager.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/BombManager.cpp.s
.PHONY : src/BombManager.cpp.s

src/CameraManager.o: src/CameraManager.cpp.o
.PHONY : src/CameraManager.o

# target to build an object file
src/CameraManager.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/CameraManager.cpp.o
.PHONY : src/CameraManager.cpp.o

src/CameraManager.i: src/CameraManager.cpp.i
.PHONY : src/CameraManager.i

# target to preprocess a source file
src/CameraManager.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/CameraManager.cpp.i
.PHONY : src/CameraManager.cpp.i

src/CameraManager.s: src/CameraManager.cpp.s
.PHONY : src/CameraManager.s

# target to generate assembly for a file
src/CameraManager.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/CameraManager.cpp.s
.PHONY : src/CameraManager.cpp.s

src/Cube.o: src/Cube.cpp.o
.PHONY : src/Cube.o

# target to build an object file
src/Cube.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Cube.cpp.o
.PHONY : src/Cube.cpp.o

src/Cube.i: src/Cube.cpp.i
.PHONY : src/Cube.i

# target to preprocess a source file
src/Cube.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Cube.cpp.i
.PHONY : src/Cube.cpp.i

src/Cube.s: src/Cube.cpp.s
.PHONY : src/Cube.s

# target to generate assembly for a file
src/Cube.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Cube.cpp.s
.PHONY : src/Cube.cpp.s

src/Explosion.o: src/Explosion.cpp.o
.PHONY : src/Explosion.o

# target to build an object file
src/Explosion.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Explosion.cpp.o
.PHONY : src/Explosion.cpp.o

src/Explosion.i: src/Explosion.cpp.i
.PHONY : src/Explosion.i

# target to preprocess a source file
src/Explosion.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Explosion.cpp.i
.PHONY : src/Explosion.cpp.i

src/Explosion.s: src/Explosion.cpp.s
.PHONY : src/Explosion.s

# target to generate assembly for a file
src/Explosion.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Explosion.cpp.s
.PHONY : src/Explosion.cpp.s

src/ExplosionManager.o: src/ExplosionManager.cpp.o
.PHONY : src/ExplosionManager.o

# target to build an object file
src/ExplosionManager.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/ExplosionManager.cpp.o
.PHONY : src/ExplosionManager.cpp.o

src/ExplosionManager.i: src/ExplosionManager.cpp.i
.PHONY : src/ExplosionManager.i

# target to preprocess a source file
src/ExplosionManager.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/ExplosionManager.cpp.i
.PHONY : src/ExplosionManager.cpp.i

src/ExplosionManager.s: src/ExplosionManager.cpp.s
.PHONY : src/ExplosionManager.s

# target to generate assembly for a file
src/ExplosionManager.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/ExplosionManager.cpp.s
.PHONY : src/ExplosionManager.cpp.s

src/FloorPanel.o: src/FloorPanel.cpp.o
.PHONY : src/FloorPanel.o

# target to build an object file
src/FloorPanel.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/FloorPanel.cpp.o
.PHONY : src/FloorPanel.cpp.o

src/FloorPanel.i: src/FloorPanel.cpp.i
.PHONY : src/FloorPanel.i

# target to preprocess a source file
src/FloorPanel.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/FloorPanel.cpp.i
.PHONY : src/FloorPanel.cpp.i

src/FloorPanel.s: src/FloorPanel.cpp.s
.PHONY : src/FloorPanel.s

# target to generate assembly for a file
src/FloorPanel.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/FloorPanel.cpp.s
.PHONY : src/FloorPanel.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameClient/Connector.o: src/GameClient/Connector.cpp.o
.PHONY : src/GameClient/Connector.o

# target to build an object file
src/GameClient/Connector.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/GameClient/Connector.cpp.o
.PHONY : src/GameClient/Connector.cpp.o

src/GameClient/Connector.i: src/GameClient/Connector.cpp.i
.PHONY : src/GameClient/Connector.i

# target to preprocess a source file
src/GameClient/Connector.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/GameClient/Connector.cpp.i
.PHONY : src/GameClient/Connector.cpp.i

src/GameClient/Connector.s: src/GameClient/Connector.cpp.s
.PHONY : src/GameClient/Connector.s

# target to generate assembly for a file
src/GameClient/Connector.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/GameClient/Connector.cpp.s
.PHONY : src/GameClient/Connector.cpp.s

src/GameClient/Listener.o: src/GameClient/Listener.cpp.o
.PHONY : src/GameClient/Listener.o

# target to build an object file
src/GameClient/Listener.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/GameClient/Listener.cpp.o
.PHONY : src/GameClient/Listener.cpp.o

src/GameClient/Listener.i: src/GameClient/Listener.cpp.i
.PHONY : src/GameClient/Listener.i

# target to preprocess a source file
src/GameClient/Listener.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/GameClient/Listener.cpp.i
.PHONY : src/GameClient/Listener.cpp.i

src/GameClient/Listener.s: src/GameClient/Listener.cpp.s
.PHONY : src/GameClient/Listener.s

# target to generate assembly for a file
src/GameClient/Listener.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/GameClient/Listener.cpp.s
.PHONY : src/GameClient/Listener.cpp.s

src/GameServer/Instance.o: src/GameServer/Instance.cpp.o
.PHONY : src/GameServer/Instance.o

# target to build an object file
src/GameServer/Instance.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/GameServer/Instance.cpp.o
.PHONY : src/GameServer/Instance.cpp.o

src/GameServer/Instance.i: src/GameServer/Instance.cpp.i
.PHONY : src/GameServer/Instance.i

# target to preprocess a source file
src/GameServer/Instance.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/GameServer/Instance.cpp.i
.PHONY : src/GameServer/Instance.cpp.i

src/GameServer/Instance.s: src/GameServer/Instance.cpp.s
.PHONY : src/GameServer/Instance.s

# target to generate assembly for a file
src/GameServer/Instance.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/GameServer/Instance.cpp.s
.PHONY : src/GameServer/Instance.cpp.s

src/GameServer/Session.o: src/GameServer/Session.cpp.o
.PHONY : src/GameServer/Session.o

# target to build an object file
src/GameServer/Session.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/GameServer/Session.cpp.o
.PHONY : src/GameServer/Session.cpp.o

src/GameServer/Session.i: src/GameServer/Session.cpp.i
.PHONY : src/GameServer/Session.i

# target to preprocess a source file
src/GameServer/Session.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/GameServer/Session.cpp.i
.PHONY : src/GameServer/Session.cpp.i

src/GameServer/Session.s: src/GameServer/Session.cpp.s
.PHONY : src/GameServer/Session.s

# target to generate assembly for a file
src/GameServer/Session.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/GameServer/Session.cpp.s
.PHONY : src/GameServer/Session.cpp.s

src/GameServer/SessionList.o: src/GameServer/SessionList.cpp.o
.PHONY : src/GameServer/SessionList.o

# target to build an object file
src/GameServer/SessionList.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/GameServer/SessionList.cpp.o
.PHONY : src/GameServer/SessionList.cpp.o

src/GameServer/SessionList.i: src/GameServer/SessionList.cpp.i
.PHONY : src/GameServer/SessionList.i

# target to preprocess a source file
src/GameServer/SessionList.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/GameServer/SessionList.cpp.i
.PHONY : src/GameServer/SessionList.cpp.i

src/GameServer/SessionList.s: src/GameServer/SessionList.cpp.s
.PHONY : src/GameServer/SessionList.s

# target to generate assembly for a file
src/GameServer/SessionList.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/GameServer/SessionList.cpp.s
.PHONY : src/GameServer/SessionList.cpp.s

src/GameWindow.o: src/GameWindow.cpp.o
.PHONY : src/GameWindow.o

# target to build an object file
src/GameWindow.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/GameWindow.cpp.o
.PHONY : src/GameWindow.cpp.o

src/GameWindow.i: src/GameWindow.cpp.i
.PHONY : src/GameWindow.i

# target to preprocess a source file
src/GameWindow.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/GameWindow.cpp.i
.PHONY : src/GameWindow.cpp.i

src/GameWindow.s: src/GameWindow.cpp.s
.PHONY : src/GameWindow.s

# target to generate assembly for a file
src/GameWindow.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/GameWindow.cpp.s
.PHONY : src/GameWindow.cpp.s

src/Input.o: src/Input.cpp.o
.PHONY : src/Input.o

# target to build an object file
src/Input.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Input.cpp.o
.PHONY : src/Input.cpp.o

src/Input.i: src/Input.cpp.i
.PHONY : src/Input.i

# target to preprocess a source file
src/Input.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Input.cpp.i
.PHONY : src/Input.cpp.i

src/Input.s: src/Input.cpp.s
.PHONY : src/Input.s

# target to generate assembly for a file
src/Input.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Input.cpp.s
.PHONY : src/Input.cpp.s

src/LocalMap.o: src/LocalMap.cpp.o
.PHONY : src/LocalMap.o

# target to build an object file
src/LocalMap.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/LocalMap.cpp.o
.PHONY : src/LocalMap.cpp.o

src/LocalMap.i: src/LocalMap.cpp.i
.PHONY : src/LocalMap.i

# target to preprocess a source file
src/LocalMap.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/LocalMap.cpp.i
.PHONY : src/LocalMap.cpp.i

src/LocalMap.s: src/LocalMap.cpp.s
.PHONY : src/LocalMap.s

# target to generate assembly for a file
src/LocalMap.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/LocalMap.cpp.s
.PHONY : src/LocalMap.cpp.s

src/LocalPlayer.o: src/LocalPlayer.cpp.o
.PHONY : src/LocalPlayer.o

# target to build an object file
src/LocalPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/LocalPlayer.cpp.o
.PHONY : src/LocalPlayer.cpp.o

src/LocalPlayer.i: src/LocalPlayer.cpp.i
.PHONY : src/LocalPlayer.i

# target to preprocess a source file
src/LocalPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/LocalPlayer.cpp.i
.PHONY : src/LocalPlayer.cpp.i

src/LocalPlayer.s: src/LocalPlayer.cpp.s
.PHONY : src/LocalPlayer.s

# target to generate assembly for a file
src/LocalPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/LocalPlayer.cpp.s
.PHONY : src/LocalPlayer.cpp.s

src/Map.o: src/Map.cpp.o
.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Map.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i
.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Map.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s
.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Map.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/NetworkIO.o: src/NetworkIO.cpp.o
.PHONY : src/NetworkIO.o

# target to build an object file
src/NetworkIO.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkIO.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkIO.cpp.o
.PHONY : src/NetworkIO.cpp.o

src/NetworkIO.i: src/NetworkIO.cpp.i
.PHONY : src/NetworkIO.i

# target to preprocess a source file
src/NetworkIO.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkIO.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkIO.cpp.i
.PHONY : src/NetworkIO.cpp.i

src/NetworkIO.s: src/NetworkIO.cpp.s
.PHONY : src/NetworkIO.s

# target to generate assembly for a file
src/NetworkIO.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkIO.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkIO.cpp.s
.PHONY : src/NetworkIO.cpp.s

src/NetworkMessage/GameEnd.o: src/NetworkMessage/GameEnd.cpp.o
.PHONY : src/NetworkMessage/GameEnd.o

# target to build an object file
src/NetworkMessage/GameEnd.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/GameEnd.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/GameEnd.cpp.o
.PHONY : src/NetworkMessage/GameEnd.cpp.o

src/NetworkMessage/GameEnd.i: src/NetworkMessage/GameEnd.cpp.i
.PHONY : src/NetworkMessage/GameEnd.i

# target to preprocess a source file
src/NetworkMessage/GameEnd.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/GameEnd.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/GameEnd.cpp.i
.PHONY : src/NetworkMessage/GameEnd.cpp.i

src/NetworkMessage/GameEnd.s: src/NetworkMessage/GameEnd.cpp.s
.PHONY : src/NetworkMessage/GameEnd.s

# target to generate assembly for a file
src/NetworkMessage/GameEnd.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/GameEnd.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/GameEnd.cpp.s
.PHONY : src/NetworkMessage/GameEnd.cpp.s

src/NetworkMessage/GameStart.o: src/NetworkMessage/GameStart.cpp.o
.PHONY : src/NetworkMessage/GameStart.o

# target to build an object file
src/NetworkMessage/GameStart.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/GameStart.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/GameStart.cpp.o
.PHONY : src/NetworkMessage/GameStart.cpp.o

src/NetworkMessage/GameStart.i: src/NetworkMessage/GameStart.cpp.i
.PHONY : src/NetworkMessage/GameStart.i

# target to preprocess a source file
src/NetworkMessage/GameStart.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/GameStart.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/GameStart.cpp.i
.PHONY : src/NetworkMessage/GameStart.cpp.i

src/NetworkMessage/GameStart.s: src/NetworkMessage/GameStart.cpp.s
.PHONY : src/NetworkMessage/GameStart.s

# target to generate assembly for a file
src/NetworkMessage/GameStart.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/GameStart.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/GameStart.cpp.s
.PHONY : src/NetworkMessage/GameStart.cpp.s

src/NetworkMessage/Join.o: src/NetworkMessage/Join.cpp.o
.PHONY : src/NetworkMessage/Join.o

# target to build an object file
src/NetworkMessage/Join.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/Join.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/Join.cpp.o
.PHONY : src/NetworkMessage/Join.cpp.o

src/NetworkMessage/Join.i: src/NetworkMessage/Join.cpp.i
.PHONY : src/NetworkMessage/Join.i

# target to preprocess a source file
src/NetworkMessage/Join.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/Join.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/Join.cpp.i
.PHONY : src/NetworkMessage/Join.cpp.i

src/NetworkMessage/Join.s: src/NetworkMessage/Join.cpp.s
.PHONY : src/NetworkMessage/Join.s

# target to generate assembly for a file
src/NetworkMessage/Join.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/Join.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/Join.cpp.s
.PHONY : src/NetworkMessage/Join.cpp.s

src/NetworkMessage/JoinAccept.o: src/NetworkMessage/JoinAccept.cpp.o
.PHONY : src/NetworkMessage/JoinAccept.o

# target to build an object file
src/NetworkMessage/JoinAccept.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/JoinAccept.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/JoinAccept.cpp.o
.PHONY : src/NetworkMessage/JoinAccept.cpp.o

src/NetworkMessage/JoinAccept.i: src/NetworkMessage/JoinAccept.cpp.i
.PHONY : src/NetworkMessage/JoinAccept.i

# target to preprocess a source file
src/NetworkMessage/JoinAccept.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/JoinAccept.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/JoinAccept.cpp.i
.PHONY : src/NetworkMessage/JoinAccept.cpp.i

src/NetworkMessage/JoinAccept.s: src/NetworkMessage/JoinAccept.cpp.s
.PHONY : src/NetworkMessage/JoinAccept.s

# target to generate assembly for a file
src/NetworkMessage/JoinAccept.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/JoinAccept.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/JoinAccept.cpp.s
.PHONY : src/NetworkMessage/JoinAccept.cpp.s

src/NetworkMessage/JoinRefuse.o: src/NetworkMessage/JoinRefuse.cpp.o
.PHONY : src/NetworkMessage/JoinRefuse.o

# target to build an object file
src/NetworkMessage/JoinRefuse.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/JoinRefuse.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/JoinRefuse.cpp.o
.PHONY : src/NetworkMessage/JoinRefuse.cpp.o

src/NetworkMessage/JoinRefuse.i: src/NetworkMessage/JoinRefuse.cpp.i
.PHONY : src/NetworkMessage/JoinRefuse.i

# target to preprocess a source file
src/NetworkMessage/JoinRefuse.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/JoinRefuse.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/JoinRefuse.cpp.i
.PHONY : src/NetworkMessage/JoinRefuse.cpp.i

src/NetworkMessage/JoinRefuse.s: src/NetworkMessage/JoinRefuse.cpp.s
.PHONY : src/NetworkMessage/JoinRefuse.s

# target to generate assembly for a file
src/NetworkMessage/JoinRefuse.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/JoinRefuse.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/JoinRefuse.cpp.s
.PHONY : src/NetworkMessage/JoinRefuse.cpp.s

src/NetworkMessage/Leave.o: src/NetworkMessage/Leave.cpp.o
.PHONY : src/NetworkMessage/Leave.o

# target to build an object file
src/NetworkMessage/Leave.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/Leave.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/Leave.cpp.o
.PHONY : src/NetworkMessage/Leave.cpp.o

src/NetworkMessage/Leave.i: src/NetworkMessage/Leave.cpp.i
.PHONY : src/NetworkMessage/Leave.i

# target to preprocess a source file
src/NetworkMessage/Leave.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/Leave.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/Leave.cpp.i
.PHONY : src/NetworkMessage/Leave.cpp.i

src/NetworkMessage/Leave.s: src/NetworkMessage/Leave.cpp.s
.PHONY : src/NetworkMessage/Leave.s

# target to generate assembly for a file
src/NetworkMessage/Leave.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/Leave.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/Leave.cpp.s
.PHONY : src/NetworkMessage/Leave.cpp.s

src/NetworkMessage/NetworkMessage.o: src/NetworkMessage/NetworkMessage.cpp.o
.PHONY : src/NetworkMessage/NetworkMessage.o

# target to build an object file
src/NetworkMessage/NetworkMessage.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/NetworkMessage.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/NetworkMessage.cpp.o
.PHONY : src/NetworkMessage/NetworkMessage.cpp.o

src/NetworkMessage/NetworkMessage.i: src/NetworkMessage/NetworkMessage.cpp.i
.PHONY : src/NetworkMessage/NetworkMessage.i

# target to preprocess a source file
src/NetworkMessage/NetworkMessage.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/NetworkMessage.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/NetworkMessage.cpp.i
.PHONY : src/NetworkMessage/NetworkMessage.cpp.i

src/NetworkMessage/NetworkMessage.s: src/NetworkMessage/NetworkMessage.cpp.s
.PHONY : src/NetworkMessage/NetworkMessage.s

# target to generate assembly for a file
src/NetworkMessage/NetworkMessage.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/NetworkMessage.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/NetworkMessage.cpp.s
.PHONY : src/NetworkMessage/NetworkMessage.cpp.s

src/NetworkMessage/NetworkMessageFactory.o: src/NetworkMessage/NetworkMessageFactory.cpp.o
.PHONY : src/NetworkMessage/NetworkMessageFactory.o

# target to build an object file
src/NetworkMessage/NetworkMessageFactory.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/NetworkMessageFactory.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/NetworkMessageFactory.cpp.o
.PHONY : src/NetworkMessage/NetworkMessageFactory.cpp.o

src/NetworkMessage/NetworkMessageFactory.i: src/NetworkMessage/NetworkMessageFactory.cpp.i
.PHONY : src/NetworkMessage/NetworkMessageFactory.i

# target to preprocess a source file
src/NetworkMessage/NetworkMessageFactory.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/NetworkMessageFactory.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/NetworkMessageFactory.cpp.i
.PHONY : src/NetworkMessage/NetworkMessageFactory.cpp.i

src/NetworkMessage/NetworkMessageFactory.s: src/NetworkMessage/NetworkMessageFactory.cpp.s
.PHONY : src/NetworkMessage/NetworkMessageFactory.s

# target to generate assembly for a file
src/NetworkMessage/NetworkMessageFactory.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/NetworkMessageFactory.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/NetworkMessageFactory.cpp.s
.PHONY : src/NetworkMessage/NetworkMessageFactory.cpp.s

src/NetworkMessage/PlayerInput.o: src/NetworkMessage/PlayerInput.cpp.o
.PHONY : src/NetworkMessage/PlayerInput.o

# target to build an object file
src/NetworkMessage/PlayerInput.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerInput.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerInput.cpp.o
.PHONY : src/NetworkMessage/PlayerInput.cpp.o

src/NetworkMessage/PlayerInput.i: src/NetworkMessage/PlayerInput.cpp.i
.PHONY : src/NetworkMessage/PlayerInput.i

# target to preprocess a source file
src/NetworkMessage/PlayerInput.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerInput.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerInput.cpp.i
.PHONY : src/NetworkMessage/PlayerInput.cpp.i

src/NetworkMessage/PlayerInput.s: src/NetworkMessage/PlayerInput.cpp.s
.PHONY : src/NetworkMessage/PlayerInput.s

# target to generate assembly for a file
src/NetworkMessage/PlayerInput.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerInput.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerInput.cpp.s
.PHONY : src/NetworkMessage/PlayerInput.cpp.s

src/NetworkMessage/PlayerJoined.o: src/NetworkMessage/PlayerJoined.cpp.o
.PHONY : src/NetworkMessage/PlayerJoined.o

# target to build an object file
src/NetworkMessage/PlayerJoined.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerJoined.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerJoined.cpp.o
.PHONY : src/NetworkMessage/PlayerJoined.cpp.o

src/NetworkMessage/PlayerJoined.i: src/NetworkMessage/PlayerJoined.cpp.i
.PHONY : src/NetworkMessage/PlayerJoined.i

# target to preprocess a source file
src/NetworkMessage/PlayerJoined.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerJoined.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerJoined.cpp.i
.PHONY : src/NetworkMessage/PlayerJoined.cpp.i

src/NetworkMessage/PlayerJoined.s: src/NetworkMessage/PlayerJoined.cpp.s
.PHONY : src/NetworkMessage/PlayerJoined.s

# target to generate assembly for a file
src/NetworkMessage/PlayerJoined.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerJoined.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerJoined.cpp.s
.PHONY : src/NetworkMessage/PlayerJoined.cpp.s

src/NetworkMessage/PlayerKilled.o: src/NetworkMessage/PlayerKilled.cpp.o
.PHONY : src/NetworkMessage/PlayerKilled.o

# target to build an object file
src/NetworkMessage/PlayerKilled.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerKilled.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerKilled.cpp.o
.PHONY : src/NetworkMessage/PlayerKilled.cpp.o

src/NetworkMessage/PlayerKilled.i: src/NetworkMessage/PlayerKilled.cpp.i
.PHONY : src/NetworkMessage/PlayerKilled.i

# target to preprocess a source file
src/NetworkMessage/PlayerKilled.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerKilled.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerKilled.cpp.i
.PHONY : src/NetworkMessage/PlayerKilled.cpp.i

src/NetworkMessage/PlayerKilled.s: src/NetworkMessage/PlayerKilled.cpp.s
.PHONY : src/NetworkMessage/PlayerKilled.s

# target to generate assembly for a file
src/NetworkMessage/PlayerKilled.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerKilled.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerKilled.cpp.s
.PHONY : src/NetworkMessage/PlayerKilled.cpp.s

src/NetworkMessage/PlayerLeft.o: src/NetworkMessage/PlayerLeft.cpp.o
.PHONY : src/NetworkMessage/PlayerLeft.o

# target to build an object file
src/NetworkMessage/PlayerLeft.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerLeft.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerLeft.cpp.o
.PHONY : src/NetworkMessage/PlayerLeft.cpp.o

src/NetworkMessage/PlayerLeft.i: src/NetworkMessage/PlayerLeft.cpp.i
.PHONY : src/NetworkMessage/PlayerLeft.i

# target to preprocess a source file
src/NetworkMessage/PlayerLeft.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerLeft.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerLeft.cpp.i
.PHONY : src/NetworkMessage/PlayerLeft.cpp.i

src/NetworkMessage/PlayerLeft.s: src/NetworkMessage/PlayerLeft.cpp.s
.PHONY : src/NetworkMessage/PlayerLeft.s

# target to generate assembly for a file
src/NetworkMessage/PlayerLeft.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/NetworkMessage/PlayerLeft.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/NetworkMessage/PlayerLeft.cpp.s
.PHONY : src/NetworkMessage/PlayerLeft.cpp.s

src/OculusCamera.o: src/OculusCamera.cpp.o
.PHONY : src/OculusCamera.o

# target to build an object file
src/OculusCamera.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/OculusCamera.cpp.o
.PHONY : src/OculusCamera.cpp.o

src/OculusCamera.i: src/OculusCamera.cpp.i
.PHONY : src/OculusCamera.i

# target to preprocess a source file
src/OculusCamera.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/OculusCamera.cpp.i
.PHONY : src/OculusCamera.cpp.i

src/OculusCamera.s: src/OculusCamera.cpp.s
.PHONY : src/OculusCamera.s

# target to generate assembly for a file
src/OculusCamera.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/OculusCamera.cpp.s
.PHONY : src/OculusCamera.cpp.s

src/OgrePlayer.o: src/OgrePlayer.cpp.o
.PHONY : src/OgrePlayer.o

# target to build an object file
src/OgrePlayer.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/OgrePlayer.cpp.o
.PHONY : src/OgrePlayer.cpp.o

src/OgrePlayer.i: src/OgrePlayer.cpp.i
.PHONY : src/OgrePlayer.i

# target to preprocess a source file
src/OgrePlayer.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/OgrePlayer.cpp.i
.PHONY : src/OgrePlayer.cpp.i

src/OgrePlayer.s: src/OgrePlayer.cpp.s
.PHONY : src/OgrePlayer.s

# target to generate assembly for a file
src/OgrePlayer.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/OgrePlayer.cpp.s
.PHONY : src/OgrePlayer.cpp.s

src/OgrePlayerList.o: src/OgrePlayerList.cpp.o
.PHONY : src/OgrePlayerList.o

# target to build an object file
src/OgrePlayerList.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/OgrePlayerList.cpp.o
.PHONY : src/OgrePlayerList.cpp.o

src/OgrePlayerList.i: src/OgrePlayerList.cpp.i
.PHONY : src/OgrePlayerList.i

# target to preprocess a source file
src/OgrePlayerList.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/OgrePlayerList.cpp.i
.PHONY : src/OgrePlayerList.cpp.i

src/OgrePlayerList.s: src/OgrePlayerList.cpp.s
.PHONY : src/OgrePlayerList.s

# target to generate assembly for a file
src/OgrePlayerList.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/OgrePlayerList.cpp.s
.PHONY : src/OgrePlayerList.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Player.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Player.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Player.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/PlayerAnimation.o: src/PlayerAnimation.cpp.o
.PHONY : src/PlayerAnimation.o

# target to build an object file
src/PlayerAnimation.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/PlayerAnimation.cpp.o
.PHONY : src/PlayerAnimation.cpp.o

src/PlayerAnimation.i: src/PlayerAnimation.cpp.i
.PHONY : src/PlayerAnimation.i

# target to preprocess a source file
src/PlayerAnimation.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/PlayerAnimation.cpp.i
.PHONY : src/PlayerAnimation.cpp.i

src/PlayerAnimation.s: src/PlayerAnimation.cpp.s
.PHONY : src/PlayerAnimation.s

# target to generate assembly for a file
src/PlayerAnimation.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/PlayerAnimation.cpp.s
.PHONY : src/PlayerAnimation.cpp.s

src/PlayerList.o: src/PlayerList.cpp.o
.PHONY : src/PlayerList.o

# target to build an object file
src/PlayerList.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/PlayerList.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/PlayerList.cpp.o
.PHONY : src/PlayerList.cpp.o

src/PlayerList.i: src/PlayerList.cpp.i
.PHONY : src/PlayerList.i

# target to preprocess a source file
src/PlayerList.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/PlayerList.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/PlayerList.cpp.i
.PHONY : src/PlayerList.cpp.i

src/PlayerList.s: src/PlayerList.cpp.s
.PHONY : src/PlayerList.s

# target to generate assembly for a file
src/PlayerList.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/PlayerList.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/PlayerList.cpp.s
.PHONY : src/PlayerList.cpp.s

src/Pyramid.o: src/Pyramid.cpp.o
.PHONY : src/Pyramid.o

# target to build an object file
src/Pyramid.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Pyramid.cpp.o
.PHONY : src/Pyramid.cpp.o

src/Pyramid.i: src/Pyramid.cpp.i
.PHONY : src/Pyramid.i

# target to preprocess a source file
src/Pyramid.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Pyramid.cpp.i
.PHONY : src/Pyramid.cpp.i

src/Pyramid.s: src/Pyramid.cpp.s
.PHONY : src/Pyramid.s

# target to generate assembly for a file
src/Pyramid.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/Pyramid.cpp.s
.PHONY : src/Pyramid.cpp.s

src/RemotePlayer.o: src/RemotePlayer.cpp.o
.PHONY : src/RemotePlayer.o

# target to build an object file
src/RemotePlayer.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/RemotePlayer.cpp.o
.PHONY : src/RemotePlayer.cpp.o

src/RemotePlayer.i: src/RemotePlayer.cpp.i
.PHONY : src/RemotePlayer.i

# target to preprocess a source file
src/RemotePlayer.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/RemotePlayer.cpp.i
.PHONY : src/RemotePlayer.cpp.i

src/RemotePlayer.s: src/RemotePlayer.cpp.s
.PHONY : src/RemotePlayer.s

# target to generate assembly for a file
src/RemotePlayer.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/RemotePlayer.cpp.s
.PHONY : src/RemotePlayer.cpp.s

src/SensorFusionDevice.o: src/SensorFusionDevice.cpp.o
.PHONY : src/SensorFusionDevice.o

# target to build an object file
src/SensorFusionDevice.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/SensorFusionDevice.cpp.o
.PHONY : src/SensorFusionDevice.cpp.o

src/SensorFusionDevice.i: src/SensorFusionDevice.cpp.i
.PHONY : src/SensorFusionDevice.i

# target to preprocess a source file
src/SensorFusionDevice.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/SensorFusionDevice.cpp.i
.PHONY : src/SensorFusionDevice.cpp.i

src/SensorFusionDevice.s: src/SensorFusionDevice.cpp.s
.PHONY : src/SensorFusionDevice.s

# target to generate assembly for a file
src/SensorFusionDevice.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/SensorFusionDevice.cpp.s
.PHONY : src/SensorFusionDevice.cpp.s

src/SimpleCamera.o: src/SimpleCamera.cpp.o
.PHONY : src/SimpleCamera.o

# target to build an object file
src/SimpleCamera.cpp.o:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/SimpleCamera.cpp.o
.PHONY : src/SimpleCamera.cpp.o

src/SimpleCamera.i: src/SimpleCamera.cpp.i
.PHONY : src/SimpleCamera.i

# target to preprocess a source file
src/SimpleCamera.cpp.i:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/SimpleCamera.cpp.i
.PHONY : src/SimpleCamera.cpp.i

src/SimpleCamera.s: src/SimpleCamera.cpp.s
.PHONY : src/SimpleCamera.s

# target to generate assembly for a file
src/SimpleCamera.cpp.s:
	$(MAKE) -f CMakeFiles/pairOculus.dir/build.make CMakeFiles/pairOculus.dir/src/SimpleCamera.cpp.s
.PHONY : src/SimpleCamera.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... pairOculus"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... src/Block.o"
	@echo "... src/Block.i"
	@echo "... src/Block.s"
	@echo "... src/BlockFactory.o"
	@echo "... src/BlockFactory.i"
	@echo "... src/BlockFactory.s"
	@echo "... src/Bomb.o"
	@echo "... src/Bomb.i"
	@echo "... src/Bomb.s"
	@echo "... src/BombManager.o"
	@echo "... src/BombManager.i"
	@echo "... src/BombManager.s"
	@echo "... src/CameraManager.o"
	@echo "... src/CameraManager.i"
	@echo "... src/CameraManager.s"
	@echo "... src/Cube.o"
	@echo "... src/Cube.i"
	@echo "... src/Cube.s"
	@echo "... src/Explosion.o"
	@echo "... src/Explosion.i"
	@echo "... src/Explosion.s"
	@echo "... src/ExplosionManager.o"
	@echo "... src/ExplosionManager.i"
	@echo "... src/ExplosionManager.s"
	@echo "... src/FloorPanel.o"
	@echo "... src/FloorPanel.i"
	@echo "... src/FloorPanel.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameClient/Connector.o"
	@echo "... src/GameClient/Connector.i"
	@echo "... src/GameClient/Connector.s"
	@echo "... src/GameClient/Listener.o"
	@echo "... src/GameClient/Listener.i"
	@echo "... src/GameClient/Listener.s"
	@echo "... src/GameServer/Instance.o"
	@echo "... src/GameServer/Instance.i"
	@echo "... src/GameServer/Instance.s"
	@echo "... src/GameServer/Session.o"
	@echo "... src/GameServer/Session.i"
	@echo "... src/GameServer/Session.s"
	@echo "... src/GameServer/SessionList.o"
	@echo "... src/GameServer/SessionList.i"
	@echo "... src/GameServer/SessionList.s"
	@echo "... src/GameWindow.o"
	@echo "... src/GameWindow.i"
	@echo "... src/GameWindow.s"
	@echo "... src/Input.o"
	@echo "... src/Input.i"
	@echo "... src/Input.s"
	@echo "... src/LocalMap.o"
	@echo "... src/LocalMap.i"
	@echo "... src/LocalMap.s"
	@echo "... src/LocalPlayer.o"
	@echo "... src/LocalPlayer.i"
	@echo "... src/LocalPlayer.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/NetworkIO.o"
	@echo "... src/NetworkIO.i"
	@echo "... src/NetworkIO.s"
	@echo "... src/NetworkMessage/GameEnd.o"
	@echo "... src/NetworkMessage/GameEnd.i"
	@echo "... src/NetworkMessage/GameEnd.s"
	@echo "... src/NetworkMessage/GameStart.o"
	@echo "... src/NetworkMessage/GameStart.i"
	@echo "... src/NetworkMessage/GameStart.s"
	@echo "... src/NetworkMessage/Join.o"
	@echo "... src/NetworkMessage/Join.i"
	@echo "... src/NetworkMessage/Join.s"
	@echo "... src/NetworkMessage/JoinAccept.o"
	@echo "... src/NetworkMessage/JoinAccept.i"
	@echo "... src/NetworkMessage/JoinAccept.s"
	@echo "... src/NetworkMessage/JoinRefuse.o"
	@echo "... src/NetworkMessage/JoinRefuse.i"
	@echo "... src/NetworkMessage/JoinRefuse.s"
	@echo "... src/NetworkMessage/Leave.o"
	@echo "... src/NetworkMessage/Leave.i"
	@echo "... src/NetworkMessage/Leave.s"
	@echo "... src/NetworkMessage/NetworkMessage.o"
	@echo "... src/NetworkMessage/NetworkMessage.i"
	@echo "... src/NetworkMessage/NetworkMessage.s"
	@echo "... src/NetworkMessage/NetworkMessageFactory.o"
	@echo "... src/NetworkMessage/NetworkMessageFactory.i"
	@echo "... src/NetworkMessage/NetworkMessageFactory.s"
	@echo "... src/NetworkMessage/PlayerInput.o"
	@echo "... src/NetworkMessage/PlayerInput.i"
	@echo "... src/NetworkMessage/PlayerInput.s"
	@echo "... src/NetworkMessage/PlayerJoined.o"
	@echo "... src/NetworkMessage/PlayerJoined.i"
	@echo "... src/NetworkMessage/PlayerJoined.s"
	@echo "... src/NetworkMessage/PlayerKilled.o"
	@echo "... src/NetworkMessage/PlayerKilled.i"
	@echo "... src/NetworkMessage/PlayerKilled.s"
	@echo "... src/NetworkMessage/PlayerLeft.o"
	@echo "... src/NetworkMessage/PlayerLeft.i"
	@echo "... src/NetworkMessage/PlayerLeft.s"
	@echo "... src/OculusCamera.o"
	@echo "... src/OculusCamera.i"
	@echo "... src/OculusCamera.s"
	@echo "... src/OgrePlayer.o"
	@echo "... src/OgrePlayer.i"
	@echo "... src/OgrePlayer.s"
	@echo "... src/OgrePlayerList.o"
	@echo "... src/OgrePlayerList.i"
	@echo "... src/OgrePlayerList.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/PlayerAnimation.o"
	@echo "... src/PlayerAnimation.i"
	@echo "... src/PlayerAnimation.s"
	@echo "... src/PlayerList.o"
	@echo "... src/PlayerList.i"
	@echo "... src/PlayerList.s"
	@echo "... src/Pyramid.o"
	@echo "... src/Pyramid.i"
	@echo "... src/Pyramid.s"
	@echo "... src/RemotePlayer.o"
	@echo "... src/RemotePlayer.i"
	@echo "... src/RemotePlayer.s"
	@echo "... src/SensorFusionDevice.o"
	@echo "... src/SensorFusionDevice.i"
	@echo "... src/SensorFusionDevice.s"
	@echo "... src/SimpleCamera.o"
	@echo "... src/SimpleCamera.i"
	@echo "... src/SimpleCamera.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

